// CEAMS / CAPE Chargemaster
// Auto-updated by the chargemaster web app on 2026-07-09T19:02:19.684Z

window.CHARGEMASTER_SEED = {
  version: "2026.1",
  sections: ["Examinations","Field Service","Hospitalizations","Diagnostics","Procedures","Supplies","Other Services","Discontinued"],
  items: [
    {"code":"1510","section":"Examinations","service":"Exotics Exam level 1","unit":"per appt","price":177,"description":"New problem visit, annual exam visit, establishing exam with no rDVM records"},
    {"code":"1513","section":"Examinations","service":"Exotics Exam level 2","unit":"per appt","price":249,"description":"Exam with rDVM records to be reviewed (relevant to referral/case)"},
    {"code":"1511","section":"Examinations","service":"Progress exam","unit":"per appt","price":116,"description":"Recheck for existing problem within 6 months; cannot be used for new problem if patient is current on annual exam"},
    {"code":"1512","section":"Examinations","service":"Emergency Exam","unit":"per appt","price":368,"description":"Walk in or same day scheduled ER"},
    {"code":"1518","section":"Examinations","service":"Wildlife exam","unit":"per appt","price":47,"description":"Charged for wild animals from wildlife rehabs, not resident/ambassador animals/client owned"},
    {"code":"1104","section":"Examinations","service":"Health Certificate","unit":"per appt","price":67,"description":"Charged in addition to exam fee when health certificate is needed"},
    {"code":"1519","section":"Examinations","service":"Tx only, no visit fee","unit":"per appt","price":0,"description":"Used when animal comes in for diagnostics and/or treatments on a day other than exam (eg when no CT slots available on exam day)"},
    {"code":"8927","section":"Examinations","service":"Tech appt","unit":"per appt","price":42,"description":"Appt completed by technician, not doctor"},
    {"code":"9031","section":"Examinations","service":"Technician time","unit":"per hour","price":93,"description":"Can be used for prolonged recovery or in any other case where a tech is needed for a prolonged time"},
    {"code":"1515","section":"Examinations","service":"Phone Consultation","unit":"per half hr","price":145,"description":"Resident/clinician consults with rdvm, zoo"},
    {"code":"8916","section":"Examinations","service":"Aquatic Animal Exam","unit":"per system","price":157,"description":"In house exam for up to 3 fish within same system; if more than 3 patients, or evaluating more than one system, use more than one exam charge; includes anesthesia and euthanasia if needed"},
    {"code":"8990","section":"Examinations","service":"Aquatic Animal Progress Check","unit":"per system","price":110,"description":"Recheck for existing problem within 6 months; cannot be used for new problem if patient is current on annual exam"},
    {"code":"8987","section":"Examinations","service":"AAH Field Call","unit":"per hour","price":300,"description":"Used when evaluating any number of fish at a client's resident; charged per hour not per patient"},
    {"code":"1560","section":"Examinations","service":"Wildlife Exam, Raptor","unit":"per exam","price":30,"description":"CRC exam"},
    {"code":"8991","section":"Examinations","service":"Telemedicine Appt","unit":"per appt","price":100,"description":"Use for AAH Telemedicine, can use for other telemedicine appointments if needed"},
    {"code":"9902","section":"Field Service","service":"Sedan Usage Charge","unit":"per day","price":150,"description":"Sedan from fleet services"},
    {"code":"9988","section":"Field Service","service":"Van Usage Charge","unit":"per day","price":291,"description":"Van/truck from fleet services"},
    {"code":"8928","section":"Field Service","service":"Drive Time","unit":"per hour","price":106,"description":"Per hour to and from destination; can be charged incrementally (rounded up to next qt hr)"},
    {"code":"8929","section":"Field Service","service":"MGZ Full day","unit":"per day","price":1477,"description":"Visit longer than 3 hours"},
    {"code":"8930","section":"Field Service","service":"MGZ Half day","unit":"per day","price":810,"description":"Visit shorter than 3 hours"},
    {"code":"8932","section":"Field Service","service":"Field Call Emergency Surcharge","unit":"per appt","price":356,"description":"Can be used for zoo/AHH for nonscheduled ERs"},
    {"code":"1501","section":"Hospitalizations","service":"Day Case","unit":"per day","price":36,"description":"Use when animal is staying for workup/not staying overnight; should NOT charge incrementally"},
    {"code":"9978","section":"Hospitalizations","service":"Aquatic Hosp Level 1","unit":"1-13 days","price":388,"description":"Hospitalization @ CABA"},
    {"code":"9979","section":"Hospitalizations","service":"Aquatic Hosp Level 2","unit":"14-31 days","price":563,"description":"Hospitalization @ CABA"},
    {"code":"1500","section":"Hospitalizations","service":"Bird (small)","unit":"per day","price":77,"description":"Budgies, cockatiels, lovebirds, conures"},
    {"code":"1505","section":"Hospitalizations","service":"Bird (medium)","unit":"per day","price":83,"description":"Amazons, African greys"},
    {"code":"1506","section":"Hospitalizations","service":"Bird (large)","unit":"per day","price":100,"description":"Cockatoos, Macaws"},
    {"code":"1502","section":"Hospitalizations","service":"Primate","unit":"per day","price":235,"description":"PPE surcharge built in"},
    {"code":"1503","section":"Hospitalizations","service":"Reptile (small)","unit":"per day","price":77,"description":"Leopard gecko, crested gecko, frogs"},
    {"code":"1544","section":"Hospitalizations","service":"Reptile (medium)","unit":"per day","price":83,"description":"Beardie, RES, desert tortoise"},
    {"code":"1545","section":"Hospitalizations","service":"Reptile (large)","unit":"per day","price":105,"description":"Iguanas, sulcata tortoises"},
    {"code":"1504","section":"Hospitalizations","service":"Small mammal 1","unit":"per day","price":77,"description":"Rats, mice, hamsters, sugar glider"},
    {"code":"1548","section":"Hospitalizations","service":"Small mammal 2","unit":"per day","price":99,"description":"Rabbits, guinea pigs, chinchillas, hedgehog"},
    {"code":"1589","section":"Hospitalizations","service":"Oxygen cage small","unit":"per day","price":171,"description":"Small snyder; Does NOT include hospitalization"},
    {"code":"1588","section":"Hospitalizations","service":"Oxygen cage large","unit":"per day","price":233,"description":"Large snyder; Does NOT include hospitalization"},
    {"code":"8933","section":"Hospitalizations","service":"Whole Room Hospitalization","unit":"per day","price":160,"description":"Use when patient occupies entire reptile room"},
    {"code":"1581","section":"Hospitalizations","service":"CAPE ICU level 1","unit":"per day","price":67,"description":"Refer to ICU level guide"},
    {"code":"1582","section":"Hospitalizations","service":"CAPE ICU level 2","unit":"per day","price":142,"description":"Refer to ICU level guide"},
    {"code":"1583","section":"Hospitalizations","service":"CAPE ICU level 3","unit":"per day","price":187,"description":"Refer to ICU level guide"},
    {"code":"1584","section":"Hospitalizations","service":"CAPE ICU level 4","unit":"per day","price":208,"description":"Refer to ICU level guide"},
    {"code":"1580","section":"Hospitalizations","service":"Infectious dz control surcharge","unit":"per day","price":113,"description":"Charged in addition to hosp if PPE is needed"},
    {"code":"1561","section":"Hospitalizations","service":"Raptor Hospitalization, small","unit":"per day","price":32,"description":"Kestrel, WESO, BANO, WTKI"},
    {"code":"1563","section":"Hospitalizations","service":"Raptor Hospitalization, medium","unit":"per day","price":37,"description":"RTHA, SWHA, GHOW"},
    {"code":"1565","section":"Hospitalizations","service":"Raptor Hospitalization, large","unit":"per day","price":45,"description":"TUVU, Eagles"},
    {"code":"1568","section":"Hospitalizations","service":"Oxygen cage, raptor","unit":"per day","price":106,"description":"Charged in addition to hospitalization for wildlife cases"},
    {"code":"8954","section":"Diagnostics","service":"PCV/TP","unit":"per test","price":26,"description":"Ran/read in CEAMS"},
    {"code":"8958","section":"Diagnostics","service":"Blood Glucose","unit":"per test","price":36,"description":"Ran/read in CEAMS with glucometer"},
    {"code":"1247","section":"Diagnostics","service":"Serial Blood Glucose","unit":"per day","price":148,"description":"Ran/read in CEAMS; can use when running 5 or more BG with glucometer"},
    {"code":"8957","section":"Diagnostics","service":"Blood smear","unit":"per test","price":25,"description":"Ran/read in CEAMS"},
    {"code":"1590","section":"Diagnostics","service":"Misc Lab test","unit":"per test","price":36,"description":"Can be used for in house cytology, fecal, other dx that we don't have code for"},
    {"code":"8959","section":"Diagnostics","service":"Fecal Occult Blood","unit":"per test","price":62,"description":"Ran/read in CEAMS"},
    {"code":"8800","section":"Diagnostics","service":"MiDog Sequencing","unit":"per test","price":273,"description":"Charge for doing test, charge for both 8800 and 8801"},
    {"code":"8801","section":"Diagnostics","service":"MiDog Kit","unit":"per test","price":25,"description":"Kit charge, charge for both 8800 and 8801"},
    {"code":"1713","section":"Diagnostics","service":"MiDog additional test","unit":"per test","price":108,"description":"Charged in addition to sequencing and kit"},
    {"code":"1556","section":"Diagnostics","service":"Sexing, blood","unit":"per bird","price":92,"description":"Send out test to Veterinary Molecular Diagnostics"},
    {"code":"1243","section":"Diagnostics","service":"Skin scrape","unit":"per test","price":60,"description":"Ran/read in CAPE"},
    {"code":"1166","section":"Diagnostics","service":"Water quality testing","unit":"per sample","price":151,"description":"Charged with 9983"},
    {"code":"9983","section":"Diagnostics","service":"Water quality interpretation","unit":"per system","price":35,"description":"Charged with 1166, but not per sample"},
    {"code":"1378","section":"Diagnostics","service":"Vetscan Avian/Rept Prof","unit":"per test","price":98,"description":"Rotor usage fee, does not include interp fee (must be charged separately)"},
    {"code":"1374","section":"Diagnostics","service":"Vetscan Comprehensive Prof","unit":"per test","price":94,"description":"Rotor usage fee, does not include interp fee (must be charged separately)"},
    {"code":"9982","section":"Diagnostics","service":"Exotic Test interp fee","unit":"per day","price":51,"description":"Should be charged for ANY test that does not come with a formal interpretation (eg CT, U/S, etc), including tests sent to outside labs; for AAH, charged per system"},
    {"code":"1536","section":"Procedures","service":"Aquatic euthanasia","unit":"per procedure","price":121,"description":"Used for when exam charge is not needed"},
    {"code":"1267","section":"Procedures","service":"Tranquilization/Sedation","unit":"per sedation","price":80,"description":"Used for injectables/intranasal sedation"},
    {"code":"1541","section":"Procedures","service":"Short inhalation","unit":"per quarter hr","price":84,"description":"Used for short instances when additional sedation is needed (ie during a CT) but does not include formal premed and induction"},
    {"code":"5001","section":"Procedures","service":"Anesthesia Induction + 15 min","unit":"per induction","price":353,"description":"Charged for both inhalant anesthesia and TIVA"},
    {"code":"5000","section":"Procedures","service":"Additional anesthesia","unit":"per quarter hr","price":66,"description":"Charged every 15 minutes of inhalant anesthesia, rounded up to nearest qtr hr; also use for TIVA"},
    {"code":"9975","section":"Procedures","service":"Anesthesia recovery","unit":"per anesthetic procedure","price":123,"description":"Charged for all anesthetic procedures"},
    {"code":"9991","section":"Procedures","service":"Post sedation recovery","unit":"per sedation","price":60,"description":"Charged when any type of post sedation monitoring is done"},
    {"code":"5208","section":"Procedures","service":"Anesthesia after hours ER surcharge","unit":"per anesthetic procedure","price":611,"description":"Charged when afterhours anesthesia is needed (ie at night or over weekend)"},
    {"code":"1550","section":"Procedures","service":"Amputation","unit":"per procedure","price":339,"description":"Toe"},
    {"code":"8934","section":"Procedures","service":"Amputation (moderate)","unit":"per procedure","price":552,"description":"Tail"},
    {"code":"8935","section":"Procedures","service":"Amputation (complex)","unit":"per procedure","price":709,"description":"Forelimb or hindlimb"},
    {"code":"2914","section":"Procedures","service":"Cystotomy","unit":"per procedure","price":1598,"description":"All species"},
    {"code":"8925","section":"Procedures","service":"Enucleation","unit":"per procedure","price":864,"description":"Removal of entire eye"},
    {"code":"1534","section":"Procedures","service":"Evisceration","unit":"per procedure","price":464,"description":"Removal of inner contents of eye, leaving sclera and muscles"},
    {"code":"9974","section":"Procedures","service":"FESSA Removal","unit":"per procedure","price":116,"description":"As described"},
    {"code":"1558","section":"Procedures","service":"Laparotomy/Celiotomy","unit":"per procedure","price":1234,"description":"Sx of abdomen or coelom, eg exploratory, FB removal, any other that doesn't have existing charge"},
    {"code":"2723","section":"Procedures","service":"Liver Lobectomy, simple","unit":"per procedure","price":2214,"description":"Caudate lobe torsion"},
    {"code":"2907","section":"Procedures","service":"Liver Lobectomy, complex","unit":"per procedure","price":2693,"description":"Anything other than caudate lobe torsion"},
    {"code":"1574","section":"Procedures","service":"Mass removal","unit":"per procedure","price":290,"description":"Charged per mass, does not include aspirates/bx/etc."},
    {"code":"9911","section":"Procedures","service":"Misc. Surgery","unit":"per procedure","price":249,"description":"Can be entered incrementally at clinicians discretion; used for any procedure that does not currently have a billing code (such as stone removal via urethra)"},
    {"code":"1570","section":"Procedures","service":"Neuter (rabbit and rodent)","unit":"per procedure","price":519,"description":"Elective, healthy animal"},
    {"code":"8936","section":"Procedures","service":"Orthopedic surgery, minor","unit":"per procedure","price":231,"description":"Single pin placement, luxation; use for all CRC ortho sx"},
    {"code":"1553","section":"Procedures","service":"Orthopedic surgery, moderate","unit":"per procedure","price":549,"description":"Simple plate/fixator"},
    {"code":"8937","section":"Procedures","service":"Orthopedic surgery, major","unit":"per procedure","price":1302,"description":"Difficult plate/fixator, multiple fx repair, circlage wire"},
    {"code":"2753","section":"Procedures","service":"PECABO/TECABO, unilateral","unit":"per procedure","price":1921,"description":"One sided partial or total ear canal ablation +/- bulla osteotomy"},
    {"code":"2784","section":"Procedures","service":"Rhinotomy","unit":"per procedure","price":1604,"description":"Charge includes nasal osteotomy and scope tower usage"},
    {"code":"9910","section":"Procedures","service":"Spay (rabbit and rodent)","unit":"per procedure","price":653,"description":"Elective, healthy animal"},
    {"code":"9101","section":"Procedures","service":"Spay, pathologic","unit":"per procedure","price":756,"description":"Disease present, does not include histo"},
    {"code":"9102","section":"Procedures","service":"Plastrotomy","unit":"per procedure","price":1880,"description":"Includes shell repair"},
    {"code":"9981","section":"Procedures","service":"Crown Reduction, incisors","unit":"per procedure","price":54,"description":"Incisors trimmed w/ high speed handpiece"},
    {"code":"1537","section":"Procedures","service":"Crown Reduction, Minor","unit":"per procedure","price":156,"description":"Clinician discretion"},
    {"code":"1538","section":"Procedures","service":"Crown Reduction, Moderate","unit":"per procedure","price":273,"description":"Clinician discretion"},
    {"code":"1551","section":"Procedures","service":"Crown Reduction, Severe","unit":"per procedure","price":464,"description":"Clinician discretion"},
    {"code":"1546","section":"Procedures","service":"Simple Extractions","unit":"per hour","price":342,"description":"No surgical incisions made"},
    {"code":"1547","section":"Procedures","service":"Surgical Extractions","unit":"per hour","price":412,"description":"Extractions made with help of surgical incision"},
    {"code":"1508","section":"Procedures","service":"Exotic teeth cleaning, minor","unit":"per procedure","price":278,"description":"Clinician discretion"},
    {"code":"1613","section":"Procedures","service":"Exotic teeth cleaning, major","unit":"per procedure","price":555,"description":"Clinician discretion"},
    {"code":"1552","section":"Procedures","service":"Abscess Marsupialization","unit":"per procedure","price":412,"description":"Includes incision, expression of abscess, wound packing, suturing"},
    {"code":"1567","section":"Procedures","service":"Air sac cannula","unit":"per procedure","price":189,"description":"Includes any supplies used"},
    {"code":"8948","section":"Procedures","service":"Beak trim","unit":"per procedure","price":87,"description":"Used for any beak trim procedure; does not include dremel bit charge"},
    {"code":"2452","section":"Procedures","service":"Biopsy Collection","unit":"per procedure","price":210,"description":"Via incision/excision, punch, Tenmo; charge is for collection only and should be used in conjunction with diagnostic testing charges"},
    {"code":"9980","section":"Procedures","service":"Egg removal, non surgical","unit":"per hour","price":296,"description":"Removal via direct visualization, ovocentesis, can charge in increments past first hour; for surgical see Laparotomy"},
    {"code":"1557","section":"Procedures","service":"Endoscopy (flexible or rigid)","unit":"per hour","price":360,"description":"Used for general endoscopic procedures, does not include instrumentation charge"},
    {"code":"8893","section":"Procedures","service":"Endoscopy (oral, aural, cloacal, aquatic)","unit":"per quarter hour","price":78,"description":"Brief or minor endoscopic procedures such as oral exam, aural exam, etc."},
    {"code":"8941","section":"Procedures","service":"Endoscopy instrumentation","unit":"per instrument","price":63,"description":"Charged per instrument (ie forceps, etc)"},
    {"code":"8942","section":"Procedures","service":"Endoscopy ER surcharge","unit":"per procedure","price":237,"description":"After hours or ER endoscopy surcharge"},
    {"code":"8965","section":"Procedures","service":"Fine needle aspirate","unit":"per procedure","price":96,"description":"FNA done in CEAMS; if ultrasound guided, charge brief u/s charge"},
    {"code":"9100","section":"Procedures","service":"Gastrointestinal decompression","unit":"per procedure","price":125,"description":"Includes supplies"},
    {"code":"9989","section":"Procedures","service":"Imping","unit":"per procedure","price":213,"description":"As described; does not include anesthesia/recovery"},
    {"code":"9976","section":"Procedures","service":"Ingluviotomy","unit":"per procedure","price":333,"description":"As described; does not include anesthesia/recovery"},
    {"code":"1559","section":"Procedures","service":"Turtle shell repair","unit":"per procedure","price":277,"description":"Includes supplies from CEAMS shell repair kit, does not include wound care charges or supplies from central service or central sterile"},
    {"code":"8943","section":"Procedures","service":"Wound care, simple","unit":"per procedure","price":51,"description":"Includes flushing, gland expression, manuka honey application, simple debridement; does not include bandaging"},
    {"code":"8944","section":"Procedures","service":"Wound care, moderate","unit":"per procedure","price":121,"description":"Includes punch biopsy aftercare, prolapse reduction, debridement by dissection; does not include bandaging"},
    {"code":"8945","section":"Procedures","service":"Wound care, complex","unit":"per procedure","price":201,"description":"Includes marsup repacking, care of multiple and/or deep wounds, incision revision; does not include bandaging"},
    {"code":"2311","section":"Procedures","service":"Wound Vacuum set up and use","unit":"per procedure","price":270,"description":"Does not include wound care or wound vac supplies; charge is for 4 weeks of use"},
    {"code":"8946","section":"Procedures","service":"Assisted Feeding <1ml","unit":"per day","price":32,"description":"Assist feeding any volume under 1 ml"},
    {"code":"1549","section":"Procedures","service":"Assisted Feeding","unit":"per day","price":62,"description":"Any volume greater than 1 ml via syringe, gavage, or etube"},
    {"code":"8947","section":"Procedures","service":"Bath, therapeutic","unit":"per bath","price":60,"description":"Does not include hair clipping; oil removal, bath to help with urine scald or fecal build up"},
    {"code":"1520","section":"Procedures","service":"Bandage, small","unit":"per procedure","price":62,"description":"Only a few materials used (ie gauze square and vetwrap, tegaderm), tape splint, small figure 8, etc."},
    {"code":"1533","section":"Procedures","service":"Bandage, medium","unit":"per procedure","price":78,"description":"Moderate amount of materials used (ie limb bandage)"},
    {"code":"1521","section":"Procedures","service":"Bandage, large","unit":"per procedure","price":97,"description":"Cast/splint made, figure 8 for large bird (ie eagle or similar)"},
    {"code":"1514","section":"Procedures","service":"Blood draw, complex","unit":"per procedure","price":47,"description":"Multiple attempts, more than normal amounts of supplies used"},
    {"code":"1284","section":"Procedures","service":"Blood pressure, indirect measurement","unit":"per day","price":77,"description":"Oscillimetric measurements or sphygmomanometer, no limit on times repeated"},
    {"code":"1527","section":"Procedures","service":"Blood transfusion","unit":"per procedure","price":665,"description":"Includes monitoring; does not include donor exam, donor blood collection, cross matching, or supplies"},
    {"code":"1523","section":"Procedures","service":"Catheter Placement, peripheral","unit":"per procedure","price":106,"description":"IV or IO with minimal attempts"},
    {"code":"9990","section":"Procedures","service":"Catheter Placement, level 2","unit":"per procedure","price":177,"description":"Multiple attempts, more than normal amount of supplies used; central line"},
    {"code":"8951","section":"Procedures","service":"Hair clip","unit":"per procedure","price":57,"description":"Sanitary clip or any other kind of requested grooming that uses scissors/clippers"},
    {"code":"1360","section":"Procedures","service":"Ear cleaning","unit":"per procedure","price":68,"description":"Ear flush with saline and/or cleaning with gauze and CTAs"},
    {"code":"1564","section":"Procedures","service":"Emergency therapy","unit":"per quarter hour","price":115,"description":"CPR therapy charge; other treatments with existing codes (ie BG or gastric decompression) should be charged in conjunction with this"},
    {"code":"8953","section":"Procedures","service":"Enema administration","unit":"per procedure","price":57,"description":"Includes supplies used"},
    {"code":"1524","section":"Procedures","service":"Euthanasia I","unit":"per procedure","price":125,"description":"Standard euth with 3 or less IVC attempts"},
    {"code":"1516","section":"Procedures","service":"Euthanasia II","unit":"per procedure","price":218,"description":"Lengthy and/or complicated euthanasias involving more than 3 IVC attempts, patient needed to be resedated, etc."},
    {"code":"1295","section":"Procedures","service":"Euthanasia no charge","unit":"per procedure","price":0,"description":"CRC and wildlife only"},
    {"code":"9972","section":"Procedures","service":"Florescein stain","unit":"per day","price":26,"description":"Stain done at CEAMS; no charge post op"},
    {"code":"8924","section":"Procedures","service":"Implant placement","unit":"per procedure","price":62,"description":"Use for deslorelin/superlorin (does not include drug cost)"},
    {"code":"1213","section":"Procedures","service":"Injection","unit":"per procedure","price":63,"description":"Used when meds aren't being charged to client (eg fish meds done at field visit)"},
    {"code":"8964","section":"Procedures","service":"Leg band removal","unit":"per procedure","price":51,"description":"As described"},
    {"code":"8952","section":"Procedures","service":"Lavage","unit":"per procedure","price":121,"description":"Trach or GI"},
    {"code":"2457","section":"Procedures","service":"Bronchoalveolar lavage","unit":"per procedure","price":98,"description":"Micro suction set up"},
    {"code":"8966","section":"Procedures","service":"Nasal flush","unit":"per procedure","price":51,"description":"Single or bilateral flush/sample collection"},
    {"code":"1202","section":"Procedures","service":"Nasogastric tube","unit":"per procedure","price":145,"description":"As described, includes supplies"},
    {"code":"1525","section":"Procedures","service":"Esophagostomy/pharyngostomy tube placement","unit":"per procedure","price":300,"description":"Includes cost of procedure and supplies, does not include single view rad charge to confirm placement"},
    {"code":"2372","section":"Procedures","service":"Urinary catheter","unit":"per procedure","price":119,"description":"Includes cost of procedure and supplies"},
    {"code":"1948","section":"Procedures","service":"Microchip placement","unit":"per procedure","price":58,"description":"Does not include microchip fee"},
    {"code":"8949","section":"Procedures","service":"Nail trim","unit":"per procedure","price":33,"description":"Charge for awake nail trims; if using dremel need to charge for bit separately"},
    {"code":"8923","section":"Procedures","service":"Nebulization","unit":"per day","price":115,"description":"15 min TID"},
    {"code":"9097","section":"Procedures","service":"Fluid Therapy, small","unit":"per procedure","price":38,"description":"SQ or IV; 0-30 ml; included in anesthesia"},
    {"code":"9098","section":"Procedures","service":"Fluid Therapy, medium","unit":"per procedure","price":50,"description":"SQ or IV; 30-250 ml; included in anesthesia"},
    {"code":"9099","section":"Procedures","service":"Fluid Therapy, large","unit":"per procedure","price":62,"description":"SQ or IV; 250-500 ml; included in anesthesia"},
    {"code":"1223","section":"Procedures","service":"Fluid Therapy, XL","unit":"per procedure","price":87,"description":"SQ or IV; 500ml+; included in anesthesia"},
    {"code":"9992","section":"Procedures","service":"Physical Therapy","unit":"per day","price":57,"description":"As described"},
    {"code":"1554","section":"Procedures","service":"U/S Brief","unit":"per procedure","price":84,"description":"Centesis charge"},
    {"code":"8950","section":"Procedures","service":"Wing trim","unit":"per procedure","price":40,"description":"As described"},
    {"code":"8897","section":"Procedures","service":"Aquatic Gonadectomy","unit":"per procedure","price":601,"description":"As described"},
    {"code":"8898","section":"Procedures","service":"Aquatic Mass Removal","unit":"per procedure","price":276,"description":"As described, does not include biopsy"},
    {"code":"1576","section":"Procedures","service":"Raptor anesthetic induction","unit":"per procedure","price":165,"description":"Includes premed, IVC, and gas induction"},
    {"code":"1577","section":"Procedures","service":"Additional anesthesia, raptor","unit":"per procedure","price":27,"description":"Can be used as additional anesthesia or as short inhalation charge for raptors"},
    {"code":"1579","section":"Procedures","service":"Raptor wound repair","unit":"per procedure","price":114,"description":"Surgical repair; if more minor can use wound care minor, moderate, or complex at CRC pricing (x 0.8)"},
    {"code":"1586","section":"Procedures","service":"Raptor bandage, small","unit":"per procedure","price":11,"description":"Clinician discretion"},
    {"code":"1587","section":"Procedures","service":"Raptor bandage, medium","unit":"per procedure","price":18,"description":"Clinician discretion"},
    {"code":"1591","section":"Procedures","service":"Raptor bandage, large","unit":"per procedure","price":26,"description":"Clinician discretion"},
    {"code":"1575","section":"Procedures","service":"Raptor mass removal","unit":"per procedure","price":139,"description":"As described, does not include biopsy"},
    {"code":"9996","section":"Supplies","service":"Misc CAPE supplies","unit":"varies","price":17,"description":""},
    {"code":"9998","section":"Supplies","service":"Misc CAPE Pharmacy","unit":"varies","price":15,"description":"When CEAMS stock is used (ie from zoo box) calculate cost by looking up drugs via pharmacy pricing, then charge in necessary increments to equal pharmacy cost"},
    {"code":"9969","section":"Supplies","service":"Dremel Bit","unit":"per bit","price":22,"description":"Charged when new bit is used"},
    {"code":"9971","section":"Supplies","service":"Manuka Honey","unit":"per tube","price":53,"description":"Charged when leaving entire tube with client; do not charge for use of in house tubes"},
    {"code":"1637","section":"Supplies","service":"CEAMS Suprelorin","unit":"per implant","price":270,"description":"Charged in conjunction with implant fee and sedation used if any"},
    {"code":"1535","section":"Discontinued","service":"Medical tx appt","unit":"per appt","price":57,"description":"Proposed discontinued: Appts should either be with dr (exam) or with technician (tech appt)","discontinued":true},
    {"code":"8931","section":"Discontinued","service":"Phone consultation (MG zoo)","unit":"per consult","price":344,"description":"Proposed discontinued: Use regular phone consult fee per Dr K request","discontinued":true},
    {"code":"8998","section":"Discontinued","service":"Aquatic Animal Consultation","unit":"per consult","price":242,"description":"Proposed discontinued: Similar in cost to AAH field call, seems redundant","discontinued":true},
    {"code":"9995","section":"Discontinued","service":"Injectable anesthesia monitoring","unit":"per procedure","price":55,"description":"Proposed discontinued: Similar in cost to addt anesthesia, confusing to know when to use","discontinued":true},
    {"code":"8901","section":"Discontinued","service":"Aquatic Necropsy","unit":"per procedure","price":128,"description":"Proposed discontinued: What is charge for? Necropsy free if done by path","discontinued":true},
    {"code":"8940","section":"Discontinued","service":"Endoscopy (flexible)","unit":"per procedure","price":439,"description":"Proposed discontinued","discontinued":true},
    {"code":"9103","section":"Discontinued","service":"Pre-femoral laparotomy","unit":"per procedure","price":1140,"description":"Proposed discontinued: Same cost as laparotomy/celiotomy charge - seems redundant","discontinued":true},
    {"code":"9977","section":"Discontinued","service":"Ovocentesis","unit":"per procedure","price":274,"description":"Proposed discontinued: Used interchangeably with egg removal charge and is same cost","discontinued":true},
    {"code":"8939","section":"Discontinued","service":"Endoscopy (celioscopy)","unit":"per procedure","price":511,"description":"Proposed discontinued: Seems redundant, have another endoscopy charge","discontinued":true},
    {"code":"9993","section":"Discontinued","service":"Otoscopy exam, minor","unit":"per procedure","price":145,"description":"Proposed discontinued: Already have another aural endoscope charge","discontinued":true},
    {"code":"1555","section":"Discontinued","service":"U/S","unit":"per procedure","price":131,"description":"Proposed discontinued: Seems like we are no longer charging for this","discontinued":true},
    {"code":"1517","section":"Discontinued","service":"CAPE Consultation","unit":"per consult","price":142,"description":"Proposed discontinued: Used when another service is primary on case and consults","discontinued":true},
    {"code":"1600","section":"Discontinued","service":"Dental prophylaxis (ferret)","unit":"per procedure","price":868,"description":"Proposed discontinued: Have exotic dental cleaning charge now, this is a dog code","discontinued":true},
    {"code":"1566","section":"Discontinued","service":"Lavage","unit":"per procedure","price":80,"description":"Proposed discontinued: Originally marked as crop wash; code looks infrequently used","discontinued":true},
    {"code":"7006","section":"Other Services","service":"CBC","unit":"per procedure","price":160,"description":"Central lab pricing"},
    {"code":"1622","section":"Other Services","service":"Group Cremation <1kg","unit":"per procedure","price":0,"description":"Pathology pricing"},
    {"code":"1623","section":"Other Services","service":"Group cremation 1-10 kg","unit":"per procedure","price":29,"description":"Pathology pricing"},
    {"code":"1624","section":"Other Services","service":"Group Cremation 10.1-30 kg","unit":"per procedure","price":57,"description":"Pathology pricing"},
    {"code":"1939","section":"Other Services","service":"Group Cremation 30.1-60 kg","unit":"per procedure","price":89,"description":"Pathology pricing"},
    {"code":"2189","section":"Examinations","service":"Group Cremation >60.1 kg","unit":"per procedure","price":112,"description":"Pathology pricing"},
    {"code":"7788","section":"Other Services","service":"Avian/Reptile Chem 1","unit":"per procedure","price":145,"description":"Central lab pricing"},
    {"code":"7789","section":"Other Services","service":"Avian/Reptile Chem 2","unit":"per procedure","price":170,"description":"Central lab pricing"},
    {"code":"7790","section":"Other Services","service":"Avian/Reptile Chem 3","unit":"per procedure","price":185,"description":"Central lab pricing"},
    {"code":"7903","section":"Other Services","service":"ICU panel","unit":"per procedure","price":87,"description":"ER pricing"},
    {"code":"7785","section":"Other Services","service":"Primate Chem 2","unit":"per procedure","price":140,"description":"Central lab pricing"},
    {"code":"7798","section":"Other Services","service":"Primate Chem 20","unit":"per procedure","price":195,"description":"Central lab receiving"},
    {"code":"7601","section":"Other Services","service":"Small Animal Chem 1","unit":"per procedure","price":192,"description":"Central lab pricing"},
    {"code":"7602","section":"Other Services","service":"Small Animal Chem 2","unit":"per procedure","price":222,"description":"Central lab pricing"},
    {"code":"7446","section":"Other Services","service":"Small Animal Chem 2 + Trig","unit":"per procedure","price":230,"description":"Central lab pricing"},
    {"code":"7568","section":"Other Services","service":"Ionized Calcium","unit":"per procedure","price":63,"description":"ER pricing"},
    {"code":"1262","section":"Other Services","service":"Protein Electrophoresis- Albumin Only","unit":"per procedure","price":39,"description":"Central lab pricing"},
    {"code":"1408","section":"Other Services","service":"Dental Radiograph, single","unit":"per procedure","price":38,"description":"DOSS pricing"},
    {"code":"6045","section":"Other Services","service":"Whole body x-ray","unit":"per procedure","price":371,"description":"Radiology pricing; 4 views"},
    {"code":"6145","section":"Other Services","service":"Whole body x-ray recheck","unit":"per procedure","price":236,"description":"Radiology pricing; 4 views"},
    {"code":"6046","section":"Other Services","service":"Whole body x-ray (raptors)","unit":"per procedure","price":233,"description":"Radiology pricing"},
    {"code":"6146","section":"Other Services","service":"Whole body x-ray recheck (raptors)","unit":"per procedure","price":152,"description":"Radiology pricing"},
    {"code":"6252","section":"Other Services","service":"Tube check","unit":"per procedure","price":133,"description":"Radiology pricing"},
    {"code":"6257","section":"Other Services","service":"Single view radiograph","unit":"per procedure","price":130,"description":"Radiology pricing; egg check or bird in box typically"},
    {"code":"6955","section":"Other Services","service":"Non Dom Ultrasound","unit":"per procedure","price":555,"description":"Ultrasound pricing"},
    {"code":"6600","section":"Other Services","service":"CT Scan (no contrast)","unit":"per procedure","price":1263,"description":"CT pricing"},
    {"code":"6610","section":"Other Services","service":"CT Scan, Add'l area","unit":"per procedure","price":805,"description":"CT pricing"},
    {"code":"6608","section":"Other Services","service":"Cone Beam CT","unit":"per procedure","price":594,"description":"DOSS pricing"},
    {"code":"6618","section":"Other Services","service":"Cone Beam CT recheck","unit":"per procedure","price":324,"description":"DOSS pricing"},
    {"code":"6650","section":"Other Services","service":"Contrast CT","unit":"per procedure","price":1701,"description":"CT pricing"},
    {"code":"1004","section":"Other Services","service":"Contrast CT, recheck (within 6 months)","unit":"per procedure","price":1192,"description":"CT pricing"},
    {"code":"6738","section":"Other Services","service":"PET CT with contrast","unit":"per procedure","price":1691,"description":"CT pricing"},
    {"code":"8989","section":"Discontinued","service":"Aquatic Animal Field Call (mileage)","unit":"Unknown","price":38,"description":"","discontinued":true}
  ]
};
